name: smartcart_espana
description: Compara precios de supermercados y ahorra dinero en tu compra semanal.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.0
  firebase_messaging: ^14.7.19
  firebase_analytics: ^10.10.0
  firebase_crashlytics: ^3.4.15
  firebase_remote_config: ^4.4.0
  google_sign_in: ^6.2.1

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.2.0

  # DI
  get_it: ^7.6.7

  # Network
  dio: ^5.4.1
  connectivity_plus: ^5.0.2

  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^0.67.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  modal_bottom_sheet: ^3.0.0
  intl: ^0.19.0
  image_picker: ^1.0.7

  # Utilities
  dartz: ^0.10.1
  rxdart: ^0.27.7
  uuid: ^4.3.3
  logger: ^2.2.0
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  barcode_scan2: ^4.3.3

  # Payments (Stripe para Premium)
  flutter_stripe: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/logos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
