"""Registra la app Android en Firebase y genera google-services.json y firebase_options.dart."""
import base64
import json
import time
from pathlib import Path

import google.auth
import google.auth.transport.requests
import google.oauth2.service_account
import requests as http

SA_PATH = Path(__file__).parent / "service_account.json"
PROJECT_ID = "cestaiq"
PACKAGE_NAME = "com.example.cestaiq"
BASE = "https://firebase.googleapis.com/v1beta1"

GOOGLE_SERVICES_OUT = Path(__file__).parent.parent / "cestaiq/android/app/google-services.json"
FIREBASE_OPTIONS_OUT = Path(__file__).parent.parent / "cestaiq/lib/firebase_options.dart"


def get_token():
    creds = google.oauth2.service_account.Credentials.from_service_account_file(
        str(SA_PATH),
        scopes=[
            "https://www.googleapis.com/auth/firebase",
            "https://www.googleapis.com/auth/cloud-platform",
        ],
    )
    creds.refresh(google.auth.transport.requests.Request())
    return creds.token


def get_or_register_android_app(headers):
    r = http.get(f"{BASE}/projects/{PROJECT_ID}/androidApps", headers=headers)
    r.raise_for_status()
    apps = r.json().get("apps", [])
    existing = next((a for a in apps if a.get("packageName") == PACKAGE_NAME), None)
    if existing:
        app_id = existing["appId"]
        print(f"App Android ya existe: {app_id}")
        return app_id

    print(f"Registrando nueva app Android ({PACKAGE_NAME})...")
    r = http.post(
        f"{BASE}/projects/{PROJECT_ID}/androidApps",
        headers=headers,
        json={"packageName": PACKAGE_NAME, "displayName": "CestaIQ"},
    )
    r.raise_for_status()
    op_name = r.json()["name"]

    for _ in range(15):
        time.sleep(3)
        r2 = http.get(f"https://firebase.googleapis.com/v1beta1/{op_name}", headers=headers)
        op_data = r2.json()
        if op_data.get("done"):
            app_id = op_data["response"]["appId"]
            print(f"App registrada: {app_id}")
            return app_id

    raise TimeoutError("Timeout esperando registro de app")


def download_google_services(app_id, headers):
    r = http.get(f"{BASE}/projects/{PROJECT_ID}/androidApps/{app_id}/config", headers=headers)
    r.raise_for_status()
    config_b64 = r.json()["configFileContents"]
    config_json = base64.b64decode(config_b64).decode()
    GOOGLE_SERVICES_OUT.write_text(config_json, encoding="utf-8")
    print(f"google-services.json -> {GOOGLE_SERVICES_OUT}")
    return json.loads(config_json)


def write_firebase_options(data):
    client = data["client"][0]
    api_key = client["api_key"][0]["current_key"]
    app_id = client["client_info"]["mobilesdk_app_id"]
    sender_id = data["project_info"]["project_number"]
    storage_bucket = data["project_info"].get("storage_bucket", f"{PROJECT_ID}.appspot.com")

    dart = f'''// Generated by setup_firebase_app.py — do not edit manually.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Plataforma no soportada: $defaultTargetPlatform');
    }}
  }}

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{sender_id}',
    projectId: '{PROJECT_ID}',
    storageBucket: '{storage_bucket}',
  );

  // iOS: añade GoogleService-Info.plist cuando configures la app iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '{api_key}',
    appId: '{app_id}',
    messagingSenderId: '{sender_id}',
    projectId: '{PROJECT_ID}',
    storageBucket: '{storage_bucket}',
    iosBundleId: 'com.example.cestaiq',
  );
}}
'''
    FIREBASE_OPTIONS_OUT.write_text(dart, encoding="utf-8")
    print(f"firebase_options.dart -> {FIREBASE_OPTIONS_OUT}")


def main():
    print("Obteniendo token de acceso...")
    token = get_token()
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    app_id = get_or_register_android_app(headers)
    data = download_google_services(app_id, headers)
    write_firebase_options(data)
    print("\nListo. La app Flutter ya apunta al proyecto Firebase real.")


if __name__ == "__main__":
    main()
